### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by radiobone** [TeslaC00/ToDo#1]
Can we make a discord group for this? I'm making commits right now and adding button which allows to change the hex color for the buttons.

**Comment by TeslaC00** [comment]
ummmmm.... i never did any work with anyone but sure here is my discord "TeslaC00#5429"

**Comment by radiobone** [comment]
ok i sent a friend request i'm cosmic_goblin.

**Comment by TeslaC00** [comment]
i am closing this let's continue talk on discord
